#  https://learngitbranching.js.org/?locale=ru_RU

- $: 'Для дальнейшей работы необходимо клонировать свой репозиторий на компьютер при помощи команды <i style=color: red>git clone</i>'
  term: cmd_1.yaml
- $: После чего перейдите в папку проекта. Установите зависимости, переименуйте файл порта и запустите сборку проекта.
  term: cmd_2.yaml
- Сделать это можно, если последовательно вводить команды, которые можно увидеть на проекторе выше
- После этих операций, можно начинать наполнять свой проект материалами.
- $: Иногда, если возникнет желание можете делать точки сохранения к которым вы можете откатиться, если что то пошло не так.
- '<i style="color: red;">git</i> - не хранит полные копии ваших дакументов. Он хранить лишь информацию об изменениях. Поэтому старые копии, не будут занимать много места на диске'
- 'Каждое сохранение называется <i style="color: orange">commit</i>'
- $: Сделать сохранение можно если ввести приведённые команды
  term: cmd_3.yaml
- '<i style="color: red">git add .</i> - эта команда регистрирует изменения в ваших файлах. Символ <i style="color: magenta">.</i> указывает на текущий каталог'
- '<i style="color: red">git commit -m "комментарий"</i> - при помощи этой команды на основе зарегестрированных файлах с изменениями делается слепок, текущего состояния проекта'
- По сути это и есть версия проекта, между которыми мы может перемещаться в случае необходимости
- После того как вы сделаете несколько коммитов, вы можете залить обновление на github.com

- jump: $root.$init